---
- name: Create CNI plugins config dir
  file:
    path: /etc/cni/net.d
    state: directory
    mode: 644

- name: Copy mynet cni plugin config
  copy:
    src: ./roles/kubelet/files/10-mynet.conf
    dest: /etc/cni/net.d/
    mode: 0644

- name: Copy loopback cni plugin config
  copy:
    src: ./roles/kubelet/files/99-loopback.conf
    dest: /etc/cni/net.d/
    mode: 0644

- name: Copy CRI config
  copy:
    src: ./roles/kubelet/files/crictl.yaml
    dest: /etc/
    mode: 0644

- name: Create configs dir for kubernetes
  file:
    path: /etc/kubernetes.d
    state: directory
    mode: 644

- name: copy kubelet manifest
  copy:
    src: ./roles/kubelet/files/KubeletConfiguration.yaml
    dest: /etc/kubernetes.d/
    mode: 0644

- name: copy kubelet service config file
  copy:
    src: ./roles/kubelet/files/20-etcd-service-manager.conf
    dest: /etc/systemd/system/kubelet.service.d/
    mode: 0644

- name: Restart containerd daemon
  systemd:
    name: containerd
    state: restarted

- name: Enable and start kubelet service
  systemd:
    name: kubelet
    daemon_reload: yes
    enabled: yes
    state: started





