apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
address: "127.0.0.1"
cgroupDriver: systemd
staticPodPath: /etc/kubernetes/manifests
authentication:
  anonymous:
    enabled: true
  webhook:
    enabled: false
authorization:
  mode: AlwaysAllow
