---
- name: Copy PCS setup script
  copy:
    src: ./roles/pcs/files/pcs_setup.sh
    dest: .
    mode: 447

- name: Run pcs_setup.sh
  shell:
    cmd: /root/pcs_setup.sh >> ./logs/pcs_stdout.log
      #    chdir: .
  delegate_to: 127.0.0.1
