---

- name: Create certs, configs; start etcd cluster
  shell:
    cmd: "./roles/certs/files/createCertsConfigs.sh >> /root/ansible/logs/task_etcd.log"
  delegate_to: 127.0.0.1

- name: Check etcd cluster health
  shell:
    cmd: "docker run --rm --net host -v /etc/kubernetes:/etc/kubernetes quay.io/coreos/etcd:v3.5.1 \
          etcdctl \
          --cert /etc/kubernetes/pki/etcd/peer.crt \
          --key /etc/kubernetes/pki/etcd/peer.key \
          --cacert /etc/kubernetes/pki/etcd/ca.crt \
          --endpoints https://192.168.234.112:2379 \
          endpoint health --cluster"
  register: check_health_output
  delegate_to: 127.0.0.1

- debug:
    var: check_health_output.stdout

